name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from VERSION.txt
        id: get_version
        run: |
          version=$(cat VERSION.txt)
          echo "version=$version" >> $GITHUB_OUTPUT
          # Check if it's a beta
          if [[ "$version" == *"-beta" ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Get commit message
        id: get_commit_msg
        run: |
          {
            echo 'commit_msg<<EOF'
            git log -1 --pretty=%B
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        run: |
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
          body: |
            ## Release Notes
            ${{ steps.get_commit_msg.outputs.commit_msg }}

            ## Docker Image
            You can pull the Docker image using:
            `docker pull szabee13/reverse-rickroll:${{ steps.get_version.outputs.version }}`
            or
            `docker pull szabee13/reverse-rickroll:latest`
            PLEASE: Read the [README](https://github.com/szabee13/reverse-rickroll/blob/main/README.md) and the [LICENSE](https://github.com/szabee13/reverse-rickroll/blob/main/LICENSE.md) before you use it.
          draft: false
          prerelease: ${{ steps.get_version.outputs.is_prerelease }}
