name: Create Release Reverse RickRoll Bot 🌀

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from VERSION.txt
        id: get_version
        run: |
          version=$(cat VERSION.txt)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get commit message
        id: get_commit_msg
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
          echo "$msg" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        run: |
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
          body: |
            ${{ steps.get_commit_msg.outputs.commit_msg }}

            docker pull ghcr.io/szabee13/reverse-rickroll:${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
